FROM --platform=linux/amd64 golang:latest

WORKDIR /app

COPY ./go.mod ./
COPY ./go.sum ./

RUN go mod download

COPY ./cmd/blog ./cmd
COPY ./pkg ./pkg

ENV GOMAXPROCS=5

RUN go build ./cmd/blog.go

EXPOSE 8080

CMD [ "./blog" ]