FROM --platform=linux/amd64 node:16-alpine AS build

WORKDIR /app

COPY ./frontend/package.json .

RUN npm install

COPY ./frontend .

RUN npm run build

FROM --platform=linux/amd64 nginx

EXPOSE 3000

COPY ./frontend/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html