pipeline {
    agent {
        kubernetes {
            defaultContainer 'jnlp'
            yaml """
            kind: Pod
            spec:
              containers:
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                imagePullPolicy: Always
                command:     
                - sleep
                args:
                - 9999999
                volumeMounts:
                - name: cfg
                  mountPath: /kaniko/.docker
              volumes:
              - name: cfg
                configMap:
                  name: config.json
            
            """
        }
    }
    stages {
        stage('checkout') {
            steps {
                git credentialsId: 'github', url: 'https://github.com/choigonyok/techlog'
            }
        }
        stage('build') {
            steps {
                script {
                    sh 'ls -a'
                    echo 'DOCKER IMAGE BUILD...'
                    container('kaniko') {
                        sh '/kaniko/executor -f ./build/Dockerfile.blog -c . --destination=achoistic98/jenkins:testtesttest'
                    }
                }
            }
        }
    }
}